# Generated by Django 4.1.5 on 2023-01-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_realtor_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
